SELECT * FROM `supple-nature-480419-g5.customer_behaviour_analysis.customers` LIMIT 1000;

#total revenue generated by male vs female
select gender,sum(purchase_amount) as revenue from `supple-nature-480419-g5.customer_behaviour_analysis.customers` group by gender;

#customers that used discount but still spent more than average purchase amount
select customer_id from `supple-nature-480419-g5.customer_behaviour_analysis.customers` where discount_applied= True and purchase_amount>= (select avg(purchase_amount) from `supple-nature-480419-g5.customer_behaviour_analysis.customers` );

#top 5 products with highest average rating

select item_purchased,ROUND(avg(review_rating),2) as Average_Review_Rating from `supple-nature-480419-g5.customer_behaviour_analysis.customers` group by item_purchased order by avg(review_rating) DESC limit 5;

#compare the average purchase amounts between standard and express shipping

select shipping_type, avg(purchase_amount) from `supple-nature-480419-g5.customer_behaviour_analysis.customers` where shipping_type in ('Standard','Express') group by shipping_type;

#compare average spend and total revenue between subscribers and non-subscribers

select subscription_status,sum(purchase_amount) as revenue, ROUND(avg(purchase_amount),2) as avg_spend, count(customer_id) as total_customers from `supple-nature-480419-g5.customer_behaviour_analysis.customers` group by subscription_status;

#5 products with highest percentage of purchases with discounts applied

